### ISSUE TITLE
Does not build on latest stable Rust (1.55)

### ISSUE THREAD

**Issue by maackle** [ptal/intervallum#19]
`bit-set 0.2.x` does not compile with the latest stable Rust (1.55). It looks like this crate needs to update its `bit-set` dependency in order to maintain compatibility with stable Rust.

Is this crate still maintained? We are using it in https://github.com/holochain/holochain, and we will need to create a fork soon if this isn't fixed upstream.

**Comment by ptal** [comment]
I created a pull request using your changes. It is now merged and the newest version is available on crates.io.

**Comment by maackle** [comment]
Thanks so much!
